### PR TITLE
[Fix] Support POST,PUT,PATCH & Fix Error when handle `kong.response.exit`

### PR DESCRIPTION
**Pull request by barockok**
Fix Kong/go-pdk#9294

### CODE REVIEW

**Comment by kikito** [comment]
@fffonion please review

**Comment by StarlightIbuki** [comment]
Hi. @barockok  Do you still want to push this forward? Please rebase the branch and solve the conflict.

**Comment by barockok** [comment]
Sure lemme do that.

**Comment by barockok** [comment]
> Hi. @barockok Do you still want to push this forward? Please rebase the branch and solve the conflict.

Done, please check 🙏

**Review by StarlightIbuki — APPROVED** [review]

**Pull request merged**
