### PR TITLE
Dependabot configuration and CI coverage

### PR DESCRIPTION
**Pull request by mmorel-35**
Define dependabot to keep gomod dependencies and github action up-to-date

### CODE REVIEW

**Comment by mmorel-35** [comment]
I still have those issues when the gloangci-lint is ran.
image


I'm not sure how to handle things here

**Comment by mmorel-35** [comment]
Only those last : 
image

Any idea on how to fix that ?

**Comment by mmorel-35** [comment]
Hi @javierguerragiraldez!
Would mind taking a look or should I just drop this PR?

**Comment by javierguerragiraldez** [comment]
H @mmorel-35 , thanks for your work on this.

But I have to say that I'm not a fan of adding bots to every repository.  also, raising the minimal required version must be done carefully.  finally, some of the style changes are due to personal preferences.

for all this, I'll have to pass on this PR.

**Pull request closed without merging**
